from solcast.pv_power_forecast import PvPowerForecast
from solcast.pv_power_estimated_actuals import PvPowerEstimatedActuals
from solcast.radiation_forecasts import RadiationForecasts

# Import as function as well
from solcast.pv_power_forecast import PvPowerForecast as pv_power_forecast
from solcast.pv_power_estimated_actuals import PvPowerEstimatedActuals as pv_power_estimated_actuals
from solcast.radiation_forecasts import RadiationForecasts as radiation_forecasts

